name: dsc180a_proj
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy>=1.20.0
  - matplotlib>=3.4.0
  - networkx>=2.5
  - pytorch>=2.0.0
  - torchvision>=0.10.0
  - torchaudio>=0.10.0
  - pip
  - pip:
      - torch-geometric>=2.0.0
